module.exports = {
  "zh": {
    "title": "联系 Bali 司机",
    "successTitle": "申请已发送",
    "successCopy": "WanderMind 会通过邮箱确认档期并转交给你选择的司机。司机私人联系方式不会公开。",
    "back": "返回路线",
    "heroTitle": "让当地司机协助路线落地",
    "heroCopy": "选择司机并填写关键行程信息。所有联系统一经 WanderMind 邮箱转交。",
    "chooseDriver": "选择司机",
    "driverRole": "Bali 本地司机",
    "estimateKicker": "透明起步价",
    "estimateTitle": "先看大概用车费用",
    "estimateCopy": "Dicky 已确认这套起步规则同样适用于 Dicky 与 Gede Nico；没有按人数加价。",
    "fullDayService": "全天包车",
    "halfDayService": "半天包车",
    "airportTransferService": "机场接送",
    "penidaService": "佩妮达行程",
    "fullDayField": "全天包车 · 10 小时",
    "halfDayField": "半天包车 · 6 小时",
    "days": "天",
    "estimateTotal": "起步估价",
    "estimateNoDays": "请选择全天或半天天数",
    "estimateFullDay": "{count} 个全天 × {price}",
    "estimateHalfDay": "{count} 个半天 × {price}",
    "estimateAirportTransfer": "机场接送按区域约 IDR 225,000–750,000，未计入上方合计",
    "estimatePenida": "佩妮达往返船票约 {price}（{people} 人）+ 岛上用车 IDR 650,000–700,000，未计入上方合计",
    "estimateNote": "含车辆、燃油、司机向导、矿泉水、停车和过路费。超时 IDR 70,000/小时，超过 30 分钟按 1 小时；特殊路线、机场、佩妮达、儿童座椅及最终金额以所选司机回复为准。当地服务由司机或供应商直接收款，WanderMind 不代收。",
    "tripSection": "你的行程",
    "routePrefill": "已带入专业路线",
    "firstName": "名字 *",
    "firstNamePlaceholder": "你的名字",
    "lastName": "姓氏",
    "optional": "可选",
    "email": "联系邮箱（可选）",
    "emailPlaceholder": "微信登录用户可不填",
    "emailHint": "已有邮箱可直接接收司机回复；微信账号不填写邮箱时，司机会通过 WanderMind 安全链接回复。",
    "startDate": "开始日期 *",
    "endDate": "结束日期 *",
    "chooseDate": "请选择",
    "people": "同行人数 *",
    "peopleUnit": "位游客",
    "pickup": "接送地点或酒店区域 *",
    "pickupPlaceholder": "例如：Ubud 酒店",
    "budget": "预算范围",
    "attractions": "想去的地点或每日路线",
    "attractionsPlaceholder": "可以直接粘贴行程",
    "intro": "补充说明",
    "introPlaceholder": "行李、航班或其他需要司机知道的信息",
    "services": "需要什么服务",
    "consent": "我同意 WanderMind 将本申请及必要联系信息转交给所选司机，仅用于确认本次行程。",
    "submit": "发送司机申请",
    "submitBusy": "正在安全转交…",
    "privacy": "不会展示司机私人电话、社交账号或个人邮箱。",
    "historyTitle": "我的司机请求",
    "refresh": "刷新",
    "loadingReplies": "正在读取回复…",
    "historyEmpty": "登录后提交的司机申请和回复会显示在这里。",
    "routeLabel": "路线",
    "replyLabel": "司机回复",
    "replyAvailable": "司机可以通过邮件中的安全链接回复一次；链接有效期 30 天。",
    "tripDays": "{days} 天行程",
    "missingTripDate": "行程日期待补充",
    "statusPending": "处理中",
    "statusSent": "已转交司机",
    "statusReplied": "司机已回复",
    "statusFailed": "等待重试",
    "loadRequestsFailed": "暂时无法读取司机回复",
    "nameRequired": "请填写姓名",
    "emailInvalid": "请填写有效邮箱",
    "guestEmailRequired": "未登录时请填写联系邮箱；微信用户可以留空",
    "dateInvalid": "请选择正确的旅行日期",
    "pickupRequired": "请填写接送地点或酒店区域",
    "consentRequired": "请确认由 WanderMind 转交申请",
    "safetyUnavailable": "内容安全校验暂不可用，请稍后重试",
    "sendFailed": "发送失败；内容已保留，请重试",
    "routeDay": "第 {day} 天：",
    "routeSeparator": "、"
  },
  "en": {
    "title": "Contact a Bali driver",
    "successTitle": "Request sent",
    "successCopy": "WanderMind will confirm availability by email and pass your request to the driver you choose. The driver's private contact details stay hidden.",
    "back": "Back to route",
    "heroTitle": "Turn your route into a real trip with local help",
    "heroCopy": "Choose a driver and share the key details. All contact goes through WanderMind email.",
    "chooseDriver": "Choose a driver",
    "driverRole": "Bali local driver",
    "estimateKicker": "Clear starting rates",
    "estimateTitle": "Estimate your driver cost",
    "estimateCopy": "Dicky has confirmed the same starting rates for Dicky and Gede Nico; there is no per-person surcharge.",
    "fullDayService": "Full-day hire",
    "halfDayService": "Half-day hire",
    "airportTransferService": "Airport transfer",
    "penidaService": "Penida trip",
    "fullDayField": "Full-day hire · 10 hours",
    "halfDayField": "Half-day hire · 6 hours",
    "days": "days",
    "estimateTotal": "Starting estimate",
    "estimateNoDays": "Select full- or half-day hire",
    "estimateFullDay": "{count} full-day hires × {price}",
    "estimateHalfDay": "{count} half-day hires × {price}",
    "estimateAirportTransfer": "Airport transfer is about IDR 225,000–750,000 by area; not included above",
    "estimatePenida": "Penida return boat tickets are about {price} ({people} travellers) + IDR 650,000–700,000 for island transport; not included above",
    "estimateNote": "Includes vehicle, fuel, driver-guide, drinking water, parking and tolls. Overtime is IDR 70,000/hour; over 30 minutes counts as one hour. Special routes, airport transfers, Penida, child seats and the final amount follow the selected driver's reply. Local services are paid directly to the driver or supplier; WanderMind does not collect payment.",
    "tripSection": "Your trip",
    "routePrefill": "Professional route added",
    "firstName": "First name *",
    "firstNamePlaceholder": "Your first name",
    "lastName": "Last name",
    "optional": "Optional",
    "email": "Contact email (optional)",
    "emailPlaceholder": "WeChat users can leave this blank",
    "emailHint": "Use an email to receive driver replies directly. Without one, WeChat users will receive a secure WanderMind link.",
    "startDate": "Start date *",
    "endDate": "End date *",
    "chooseDate": "Choose",
    "people": "Travellers *",
    "peopleUnit": "travellers",
    "pickup": "Pickup point or hotel area *",
    "pickupPlaceholder": "e.g. Ubud hotel",
    "budget": "Budget range",
    "attractions": "Places or daily route",
    "attractionsPlaceholder": "Paste an itinerary if you have one",
    "intro": "Additional notes",
    "introPlaceholder": "Luggage, flights or anything the driver should know",
    "services": "What do you need?",
    "consent": "I agree that WanderMind may pass this request and necessary contact details to the selected driver for this trip only.",
    "submit": "Send driver request",
    "submitBusy": "Sending securely…",
    "privacy": "We never display a driver's private phone number, social account or personal email.",
    "historyTitle": "My driver requests",
    "refresh": "Refresh",
    "loadingReplies": "Loading replies…",
    "historyEmpty": "Driver requests and replies submitted after sign-in will appear here.",
    "routeLabel": "Route",
    "replyLabel": "Driver reply",
    "replyAvailable": "The driver can reply once through the secure link in the email. The link is valid for 30 days.",
    "tripDays": "{days}-day trip",
    "missingTripDate": "Trip dates not provided",
    "statusPending": "Processing",
    "statusSent": "Sent to driver",
    "statusReplied": "Driver replied",
    "statusFailed": "Retry needed",
    "loadRequestsFailed": "Driver replies are temporarily unavailable",
    "nameRequired": "Enter your name",
    "emailInvalid": "Enter a valid email",
    "guestEmailRequired": "Add a contact email when signed out; WeChat users can leave it blank",
    "dateInvalid": "Choose valid trip dates",
    "pickupRequired": "Enter a pickup point or hotel area",
    "consentRequired": "Confirm that WanderMind may forward the request",
    "safetyUnavailable": "Content safety check is temporarily unavailable. Try again later.",
    "sendFailed": "Could not send. Your details were kept; please try again.",
    "routeDay": "Day {day}: ",
    "routeSeparator": ", "
  },
  "ja": {
    "title": "バリのドライバーに相談",
    "successTitle": "依頼を送信しました",
    "successCopy": "WanderMind がメールで空き状況を確認し、選択したドライバーへ依頼を届けます。ドライバーの個人連絡先は公開されません。",
    "back": "ルートに戻る",
    "heroTitle": "現地ドライバーと旅を実現",
    "heroCopy": "ドライバーを選び、旅の要点を入力してください。連絡はすべて WanderMind のメール経由です。",
    "chooseDriver": "ドライバーを選ぶ",
    "driverRole": "バリ現地ドライバー",
    "estimateKicker": "明快な基本料金",
    "estimateTitle": "車の料金目安を見る",
    "estimateCopy": "Dicky が確認した基本料金は Dicky と Gede Nico の両方に適用され、人数による追加料金はありません。",
    "fullDayService": "終日チャーター",
    "halfDayService": "半日チャーター",
    "airportTransferService": "空港送迎",
    "penidaService": "ペニダ行程",
    "fullDayField": "終日チャーター · 10時間",
    "halfDayField": "半日チャーター · 6時間",
    "days": "日",
    "estimateTotal": "基本料金の目安",
    "estimateNoDays": "終日または半日の日数を選択してください",
    "estimateFullDay": "終日 {count}日 × {price}",
    "estimateHalfDay": "半日 {count}日 × {price}",
    "estimateAirportTransfer": "空港送迎はエリアにより約 IDR 225,000–750,000。上の合計には含まれません",
    "estimatePenida": "ペニダ往復ボートは約 {price}（{people}人）+ 島内移動 IDR 650,000–700,000。上の合計には含まれません",
    "estimateNote": "車両、燃料、ドライバーガイド、飲料水、駐車場、通行料を含みます。延長は1時間 IDR 70,000、30分を超えると1時間分です。特別ルート、空港送迎、ペニダ、チャイルドシート、最終料金は選択したドライバーの返信をご確認ください。現地サービスの支払いはドライバーまたは業者へ直接行い、WanderMind は集金しません。",
    "tripSection": "旅行の内容",
    "routePrefill": "プロルートを反映済み",
    "firstName": "名 *",
    "firstNamePlaceholder": "名を入力",
    "lastName": "姓",
    "optional": "任意",
    "email": "連絡先メール（任意）",
    "emailPlaceholder": "WeChatログインは空欄可",
    "emailHint": "メールアドレスがあればドライバーの返信を直接受け取れます。未入力の場合は WanderMind の安全なリンクで返信します。",
    "startDate": "開始日 *",
    "endDate": "終了日 *",
    "chooseDate": "選択してください",
    "people": "同行人数 *",
    "peopleUnit": "名",
    "pickup": "送迎場所またはホテルエリア *",
    "pickupPlaceholder": "例：ウブドのホテル",
    "budget": "予算の目安",
    "attractions": "行きたい場所または日ごとのルート",
    "attractionsPlaceholder": "旅程をそのまま貼り付けできます",
    "intro": "補足事項",
    "introPlaceholder": "荷物、フライト、ドライバーへの連絡事項",
    "services": "必要なサービス",
    "consent": "この旅行の確認に限り、WanderMind が依頼内容と必要な連絡先を選択したドライバーへ渡すことに同意します。",
    "submit": "ドライバーに依頼を送る",
    "submitBusy": "安全に送信中…",
    "privacy": "ドライバーの個人電話番号、SNS、個人メールは表示しません。",
    "historyTitle": "ドライバー依頼履歴",
    "refresh": "更新",
    "loadingReplies": "返信を読み込み中…",
    "historyEmpty": "ログイン後に送信したドライバー依頼と返信がここに表示されます。",
    "routeLabel": "ルート",
    "replyLabel": "ドライバーからの返信",
    "replyAvailable": "メールの安全なリンクから、ドライバーが1回返信できます。リンクの有効期限は30日です。",
    "tripDays": "{days}日間の旅行",
    "missingTripDate": "旅行日程は未入力です",
    "statusPending": "処理中",
    "statusSent": "ドライバーへ転送済み",
    "statusReplied": "ドライバーが返信済み",
    "statusFailed": "再送待ち",
    "loadRequestsFailed": "ドライバーの返信を一時的に読み込めません",
    "nameRequired": "名前を入力してください",
    "emailInvalid": "有効なメールアドレスを入力してください",
    "guestEmailRequired": "未ログインの場合は連絡先メールを入力してください。WeChatユーザーは空欄でも送信できます",
    "dateInvalid": "正しい旅行日程を選択してください",
    "pickupRequired": "送迎場所またはホテルエリアを入力してください",
    "consentRequired": "WanderMind から依頼を転送することを確認してください",
    "safetyUnavailable": "コンテンツ安全確認を一時的に利用できません。後でもう一度お試しください。",
    "sendFailed": "送信できませんでした。入力内容は保持されています。もう一度お試しください。",
    "routeDay": "{day}日目：",
    "routeSeparator": "、"
  },
  "ko": {
    "title": "발리 기사에게 문의",
    "successTitle": "요청을 보냈어요",
    "successCopy": "WanderMind가 이메일로 일정을 확인한 뒤 선택한 기사에게 요청을 전달합니다. 기사의 개인 연락처는 공개되지 않습니다.",
    "back": "경로로 돌아가기",
    "heroTitle": "현지 기사와 여행을 현실로",
    "heroCopy": "기사를 선택하고 여행 정보를 입력하세요. 모든 연락은 WanderMind 이메일을 통해 전달됩니다.",
    "chooseDriver": "기사 선택",
    "driverRole": "발리 현지 기사",
    "estimateKicker": "투명한 시작 요금",
    "estimateTitle": "차량 이용료 미리 보기",
    "estimateCopy": "Dicky가 확인한 시작 요금은 Dicky와 Gede Nico 모두에게 적용되며, 인원 추가 요금은 없습니다.",
    "fullDayService": "종일 차량",
    "halfDayService": "반일 차량",
    "airportTransferService": "공항 픽업",
    "penidaService": "페니다 일정",
    "fullDayField": "종일 차량 · 10시간",
    "halfDayField": "반일 차량 · 6시간",
    "days": "일",
    "estimateTotal": "시작 예상 금액",
    "estimateNoDays": "종일 또는 반일 일수를 선택하세요",
    "estimateFullDay": "종일 {count}일 × {price}",
    "estimateHalfDay": "반일 {count}일 × {price}",
    "estimateAirportTransfer": "공항 픽업은 지역에 따라 약 IDR 225,000–750,000이며 위 합계에 포함되지 않습니다",
    "estimatePenida": "페니다 왕복 보트는 약 {price}({people}명) + 섬 내 차량 IDR 650,000–700,000이며 위 합계에 포함되지 않습니다",
    "estimateNote": "차량, 연료, 기사 가이드, 생수, 주차비와 통행료가 포함됩니다. 초과 이용은 시간당 IDR 70,000이며 30분을 넘으면 1시간으로 계산합니다. 특별 경로, 공항 픽업, 페니다, 어린이 카시트와 최종 금액은 선택한 기사의 답변을 따릅니다. 현지 서비스 비용은 기사 또는 공급자에게 직접 지불하며 WanderMind가 받지 않습니다.",
    "tripSection": "여행 일정",
    "routePrefill": "전문 경로가 입력됨",
    "firstName": "이름 *",
    "firstNamePlaceholder": "이름을 입력하세요",
    "lastName": "성",
    "optional": "선택 사항",
    "email": "연락 이메일 (선택)",
    "emailPlaceholder": "WeChat 로그인 사용자는 비워도 됩니다",
    "emailHint": "이메일을 입력하면 기사 답변을 바로 받을 수 있습니다. 비워 두면 WanderMind 보안 링크로 답변을 받습니다.",
    "startDate": "시작일 *",
    "endDate": "종료일 *",
    "chooseDate": "선택하세요",
    "people": "여행 인원 *",
    "peopleUnit": "명",
    "pickup": "픽업 장소 또는 호텔 지역 *",
    "pickupPlaceholder": "예: 우붓 호텔",
    "budget": "예산 범위",
    "attractions": "가고 싶은 곳 또는 일일 경로",
    "attractionsPlaceholder": "일정을 그대로 붙여 넣을 수 있어요",
    "intro": "추가 메모",
    "introPlaceholder": "짐, 항공편 또는 기사에게 알릴 내용",
    "services": "필요한 서비스",
    "consent": "이번 여행 확인을 위해 WanderMind가 이 요청과 필요한 연락처를 선택한 기사에게 전달하는 데 동의합니다.",
    "submit": "기사에게 요청 보내기",
    "submitBusy": "안전하게 전송 중…",
    "privacy": "기사의 개인 전화번호, 소셜 계정 또는 개인 이메일은 표시하지 않습니다.",
    "historyTitle": "내 기사 요청",
    "refresh": "새로고침",
    "loadingReplies": "답변을 불러오는 중…",
    "historyEmpty": "로그인 후 제출한 기사 요청과 답변이 여기에 표시됩니다.",
    "routeLabel": "경로",
    "replyLabel": "기사 답변",
    "replyAvailable": "이메일의 보안 링크를 통해 기사가 한 번 답변할 수 있습니다. 링크는 30일 동안 유효합니다.",
    "tripDays": "{days}일 여행",
    "missingTripDate": "여행 날짜가 아직 없습니다",
    "statusPending": "처리 중",
    "statusSent": "기사에게 전달됨",
    "statusReplied": "기사가 답변함",
    "statusFailed": "재시도 필요",
    "loadRequestsFailed": "기사 답변을 잠시 불러올 수 없습니다",
    "nameRequired": "이름을 입력하세요",
    "emailInvalid": "유효한 이메일을 입력하세요",
    "guestEmailRequired": "로그아웃 상태에서는 연락 이메일을 입력하세요. WeChat 사용자는 비워도 됩니다",
    "dateInvalid": "올바른 여행 날짜를 선택하세요",
    "pickupRequired": "픽업 장소 또는 호텔 지역을 입력하세요",
    "consentRequired": "WanderMind가 요청을 전달하는 데 동의했는지 확인하세요",
    "safetyUnavailable": "콘텐츠 안전 확인을 잠시 사용할 수 없습니다. 나중에 다시 시도하세요.",
    "sendFailed": "보내지 못했습니다. 입력 내용은 보관했으니 다시 시도하세요.",
    "routeDay": "{day}일차: ",
    "routeSeparator": ", "
  },
  "id": {
    "title": "Hubungi driver Bali",
    "successTitle": "Permintaan terkirim",
    "successCopy": "WanderMind akan mengonfirmasi ketersediaan lewat email dan meneruskan permintaan kepada driver pilihan Anda. Kontak pribadi driver tidak ditampilkan.",
    "back": "Kembali ke rute",
    "heroTitle": "Wujudkan rute Anda bersama driver lokal",
    "heroCopy": "Pilih driver dan isi detail penting perjalanan. Semua komunikasi diteruskan lewat email WanderMind.",
    "chooseDriver": "Pilih driver",
    "driverRole": "Driver lokal Bali",
    "estimateKicker": "Tarif awal yang jelas",
    "estimateTitle": "Lihat perkiraan biaya kendaraan",
    "estimateCopy": "Dicky telah mengonfirmasi tarif awal yang sama untuk Dicky dan Gede Nico; tidak ada biaya tambahan per orang.",
    "fullDayService": "Sewa seharian",
    "halfDayService": "Sewa setengah hari",
    "airportTransferService": "Antar-jemput bandara",
    "penidaService": "Perjalanan Penida",
    "fullDayField": "Sewa seharian · 10 jam",
    "halfDayField": "Sewa setengah hari · 6 jam",
    "days": "hari",
    "estimateTotal": "Perkiraan tarif awal",
    "estimateNoDays": "Pilih jumlah hari penuh atau setengah hari",
    "estimateFullDay": "{count} hari penuh × {price}",
    "estimateHalfDay": "{count} setengah hari × {price}",
    "estimateAirportTransfer": "Antar-jemput bandara sekitar IDR 225,000–750,000 sesuai area; belum termasuk di atas",
    "estimatePenida": "Tiket kapal pulang-pergi Penida sekitar {price} ({people} tamu) + transportasi pulau IDR 650,000–700,000; belum termasuk di atas",
    "estimateNote": "Termasuk kendaraan, bahan bakar, pemandu sekaligus driver, air minum, parkir, dan tol. Kelebihan waktu dikenai IDR 70,000/jam; lebih dari 30 menit dihitung 1 jam. Rute khusus, antar-jemput bandara, Penida, kursi anak, dan jumlah akhir mengikuti balasan driver pilihan Anda. Layanan lokal dibayar langsung kepada driver atau pemasok; WanderMind tidak menerima pembayaran.",
    "tripSection": "Perjalanan Anda",
    "routePrefill": "Rute profesional sudah dimasukkan",
    "firstName": "Nama depan *",
    "firstNamePlaceholder": "Nama depan Anda",
    "lastName": "Nama belakang",
    "optional": "Opsional",
    "email": "Email kontak (opsional)",
    "emailPlaceholder": "Pengguna WeChat boleh mengosongkannya",
    "emailHint": "Dengan email, Anda dapat menerima balasan driver secara langsung. Jika kosong, driver akan membalas melalui tautan aman WanderMind.",
    "startDate": "Tanggal mulai *",
    "endDate": "Tanggal selesai *",
    "chooseDate": "Pilih",
    "people": "Jumlah tamu *",
    "peopleUnit": "tamu",
    "pickup": "Lokasi jemput atau area hotel *",
    "pickupPlaceholder": "contoh: hotel di Ubud",
    "budget": "Kisaran anggaran",
    "attractions": "Tempat tujuan atau rute harian",
    "attractionsPlaceholder": "Tempel rencana perjalanan jika ada",
    "intro": "Catatan tambahan",
    "introPlaceholder": "Bagasi, penerbangan, atau hal yang perlu diketahui driver",
    "services": "Layanan yang dibutuhkan",
    "consent": "Saya setuju WanderMind meneruskan permintaan ini dan kontak yang diperlukan kepada driver pilihan hanya untuk mengonfirmasi perjalanan ini.",
    "submit": "Kirim permintaan driver",
    "submitBusy": "Mengirim dengan aman…",
    "privacy": "Kami tidak menampilkan nomor telepon, akun sosial, atau email pribadi driver.",
    "historyTitle": "Permintaan driver saya",
    "refresh": "Muat ulang",
    "loadingReplies": "Memuat balasan…",
    "historyEmpty": "Permintaan dan balasan driver yang dikirim setelah masuk akan muncul di sini.",
    "routeLabel": "Rute",
    "replyLabel": "Balasan driver",
    "replyAvailable": "Driver dapat membalas sekali melalui tautan aman dalam email. Tautan berlaku selama 30 hari.",
    "tripDays": "Perjalanan {days} hari",
    "missingTripDate": "Tanggal perjalanan belum diisi",
    "statusPending": "Sedang diproses",
    "statusSent": "Diteruskan ke driver",
    "statusReplied": "Driver sudah membalas",
    "statusFailed": "Perlu dicoba lagi",
    "loadRequestsFailed": "Balasan driver sementara tidak tersedia",
    "nameRequired": "Isi nama Anda",
    "emailInvalid": "Isi email yang valid",
    "guestEmailRequired": "Saat belum masuk, isi email kontak. Pengguna WeChat boleh mengosongkannya",
    "dateInvalid": "Pilih tanggal perjalanan yang benar",
    "pickupRequired": "Isi lokasi jemput atau area hotel",
    "consentRequired": "Konfirmasikan bahwa WanderMind boleh meneruskan permintaan",
    "safetyUnavailable": "Pemeriksaan keamanan konten sementara tidak tersedia. Coba lagi nanti.",
    "sendFailed": "Tidak dapat mengirim. Data Anda disimpan; silakan coba lagi.",
    "routeDay": "Hari ke-{day}: ",
    "routeSeparator": ", "
  }
};
