module.exports = {
  "zh": {
    "hero": "把路线、机酒与当地司机接到同一段旅程",
    "login": "登录",
    "register": "注册",
    "name": "昵称",
    "nameHint": "例如：小峰",
    "email": "邮箱",
    "code": "邮箱验证码",
    "codeHint": "6 位数字",
    "sendCode": "发送验证码",
    "password": "密码",
    "passwordHint": "至少 6 位",
    "or": "或",
    "wechatBusy": "正在连接微信…",
    "wechatLogin": "微信一键登录",
    "linkHint": "已有邮箱账号请先用邮箱登录，再在首页绑定微信，避免形成两个独立账号。",
    "expiry": "验证码 10 分钟内有效；60 秒后可重新发送。",
    "hello": "你好，",
    "where": "先从巴厘岛开始：看真实地点，排一条能落地的路线。",
    "other": "输入其他目的地…",
    "linkTitle": "绑定微信账号",
    "linkCopy": "下次可直接使用微信登录，不会合并其他账号",
    "link": "绑定",
    "linked": "微信账号已绑定",
    "start": "从这里开始",
    "ask": "问旅行问题",
    "advice": "获得具体建议",
    "compare": "机酒比价",
    "options": "查看酒店与机票",
    "trips": "我的行程",
    "continue": "继续路线安排",
    "prefs": "旅行偏好",
    "habits": "记下你的习惯",
    "moments": "岛屿上的真实瞬间",
    "galleryCopy": "浏览已授权作品，点开地点可看不同景色与旅行提示。",
    "gallery": "进入作品集",
    "logout": "退出登录",
    "logoutAsk": "确定要退出当前账号吗？",
    "validEmail": "请先填写有效邮箱",
    "codeSent": "验证码已发送",
    "codeFailed": "验证码发送失败，请重试",
    "required": "请填写邮箱和密码",
    "passwordShort": "密码至少 6 位",
    "nameRequired": "请填写昵称",
    "codeRequired": "请输入邮件中的 6 位验证码",
    "welcome": "欢迎回来",
    "registered": "注册成功",
    "failed": "操作失败",
    "wechatError": "微信登录暂不可用，请稍后重试",
    "wechatSuccess": "微信登录成功",
    "linkError": "微信绑定暂不可用，请稍后重试",
    "destination": "输入目的地",
    "destinationHint": "如：东京、纽约、首尔…",
    "selected": "已设为 ",
    "bali": "巴厘岛",
    "kyoto": "京都",
    "paris": "巴黎",
    "santorini": "圣托里尼",
    "indonesia": "印度尼西亚",
    "japan": "日本",
    "france": "法国",
    "greece": "希腊",
    "confirm": "确定",
    "cancel": "取消"
  },
  "en": {
    "hero": "Plan your trip, compare stays and connect with local drivers",
    "login": "Sign in",
    "register": "Sign up",
    "name": "Name",
    "nameHint": "Your name",
    "email": "Email",
    "code": "Email code",
    "codeHint": "6 digits",
    "sendCode": "Send code",
    "password": "Password",
    "passwordHint": "At least 6 characters",
    "or": "or",
    "wechatBusy": "Connecting to WeChat…",
    "wechatLogin": "Continue with WeChat",
    "linkHint": "Already have an email account? Sign in with email, then link WeChat to avoid a second account.",
    "expiry": "Code expires in 10 minutes. Resend after 60 seconds.",
    "hello": "Hello, ",
    "where": "Start with Bali: real places and a route you can actually use.",
    "other": "Enter another destination…",
    "linkTitle": "Link WeChat",
    "linkCopy": "Use WeChat next time. Other accounts will not be merged.",
    "link": "Link",
    "linked": "WeChat linked",
    "start": "Start here",
    "ask": "Ask about travel",
    "advice": "Get practical advice",
    "compare": "Compare travel options",
    "options": "Explore available options",
    "trips": "My trips",
    "continue": "Continue planning",
    "prefs": "Travel preferences",
    "habits": "Save what you enjoy",
    "moments": "Moments from the island",
    "galleryCopy": "Explore photos, places and tips for your trip.",
    "gallery": "Explore photos",
    "logout": "Sign out",
    "logoutAsk": "Sign out of this account?",
    "validEmail": "Enter a valid email first",
    "codeSent": "Code sent",
    "codeFailed": "Could not send code. Retry.",
    "required": "Enter email and password",
    "passwordShort": "Password needs 6 characters",
    "nameRequired": "Enter your name",
    "codeRequired": "Enter the 6-digit email code",
    "welcome": "Welcome back",
    "registered": "Account created",
    "failed": "Could not complete. Retry.",
    "wechatError": "WeChat sign-in unavailable. Retry later.",
    "wechatSuccess": "Signed in with WeChat",
    "linkError": "Could not link WeChat. Retry later.",
    "destination": "Enter destination",
    "destinationHint": "Tokyo, New York, Seoul…",
    "selected": "Selected: ",
    "bali": "Bali",
    "kyoto": "Kyoto",
    "paris": "Paris",
    "santorini": "Santorini",
    "indonesia": "Indonesia",
    "japan": "Japan",
    "france": "France",
    "greece": "Greece",
    "confirm": "OK",
    "cancel": "Cancel"
  },
  "ja": {
    "hero": "旅の計画から宿泊探し、地元ドライバーへの相談まで",
    "login": "ログイン",
    "register": "新規登録",
    "name": "ニックネーム",
    "nameHint": "お名前",
    "email": "メール",
    "code": "メール認証コード",
    "codeHint": "6桁の数字",
    "sendCode": "コード送信",
    "password": "パスワード",
    "passwordHint": "6文字以上",
    "or": "または",
    "wechatBusy": "WeChatに接続中…",
    "wechatLogin": "WeChatでログイン",
    "linkHint": "メールで登録済みの方はメールでログイン後、WeChatを連携してください。アカウントの重複を防げます。",
    "expiry": "コードは10分間有効です。60秒後に再送できます。",
    "hello": "こんにちは、",
    "where": "まずはバリから。実在する場所と、現地で使えるルートを見てみましょう。",
    "other": "ほかの目的地を入力…",
    "linkTitle": "WeChatを連携",
    "linkCopy": "次回はWeChatでログインできます。別のアカウントは統合されません。",
    "link": "連携",
    "linked": "WeChat連携済み",
    "start": "ここから始める",
    "ask": "旅の相談",
    "advice": "具体的なアドバイス",
    "compare": "航空券・宿泊を比較",
    "options": "選択肢を探す",
    "trips": "旅程",
    "continue": "計画を続ける",
    "prefs": "旅の好み",
    "habits": "好みを保存",
    "moments": "島のひととき",
    "galleryCopy": "写真や場所、旅のヒントを見つけましょう。",
    "gallery": "写真を見る",
    "logout": "ログアウト",
    "logoutAsk": "ログアウトしますか？",
    "validEmail": "有効なメールを入力してください",
    "codeSent": "コードを送信しました",
    "codeFailed": "送信できませんでした。再試行してください。",
    "required": "メールとパスワードを入力してください",
    "passwordShort": "パスワードは6文字以上です",
    "nameRequired": "ニックネームを入力してください",
    "codeRequired": "メールの6桁コードを入力してください",
    "welcome": "おかえりなさい",
    "registered": "登録しました",
    "failed": "完了できませんでした。再試行してください。",
    "wechatError": "WeChatログインを後でもう一度お試しください。",
    "wechatSuccess": "WeChatでログインしました",
    "linkError": "WeChat連携を後でもう一度お試しください。",
    "destination": "目的地を入力",
    "destinationHint": "東京、ニューヨーク、ソウルなど",
    "selected": "選択：",
    "bali": "バリ島",
    "kyoto": "京都",
    "paris": "パリ",
    "santorini": "サントリーニ",
    "indonesia": "インドネシア",
    "japan": "日本",
    "france": "フランス",
    "greece": "ギリシャ",
    "confirm": "OK",
    "cancel": "キャンセル"
  },
  "ko": {
    "hero": "여행 계획부터 숙소 비교와 현지 기사 문의까지",
    "login": "로그인",
    "register": "가입",
    "name": "이름",
    "nameHint": "이름 입력",
    "email": "이메일",
    "code": "이메일 인증번호",
    "codeHint": "숫자 6자리",
    "sendCode": "인증번호 보내기",
    "password": "비밀번호",
    "passwordHint": "6자 이상",
    "or": "또는",
    "wechatBusy": "WeChat 연결 중…",
    "wechatLogin": "WeChat으로 로그인",
    "linkHint": "이메일 계정이 있다면 먼저 이메일로 로그인한 뒤 WeChat을 연결하세요. 계정 중복을 방지합니다.",
    "expiry": "인증번호는 10분간 유효하며 60초 후 재전송할 수 있습니다.",
    "hello": "안녕하세요, ",
    "where": "먼저 발리부터 만나보세요. 실제 장소와 바로 쓸 수 있는 여행 경로를 준비했습니다.",
    "other": "다른 목적지 입력…",
    "linkTitle": "WeChat 연결",
    "linkCopy": "다음에는 WeChat으로 로그인하세요. 다른 계정과 병합되지 않습니다.",
    "link": "연결",
    "linked": "WeChat 연결됨",
    "start": "여기서 시작",
    "ask": "여행 질문",
    "advice": "구체적인 조언 받기",
    "compare": "항공·숙소 비교",
    "options": "여행 옵션 살펴보기",
    "trips": "내 여행",
    "continue": "계획 이어가기",
    "prefs": "여행 취향",
    "habits": "취향 저장",
    "moments": "섬에서 만난 순간",
    "galleryCopy": "사진과 장소, 여행 팁을 살펴보세요.",
    "gallery": "사진 둘러보기",
    "logout": "로그아웃",
    "logoutAsk": "이 계정에서 로그아웃할까요?",
    "validEmail": "유효한 이메일을 입력하세요",
    "codeSent": "인증번호 전송됨",
    "codeFailed": "전송하지 못했습니다. 다시 시도하세요.",
    "required": "이메일과 비밀번호를 입력하세요",
    "passwordShort": "비밀번호는 6자 이상이어야 합니다",
    "nameRequired": "이름을 입력하세요",
    "codeRequired": "이메일의 6자리 인증번호를 입력하세요",
    "welcome": "다시 오신 것을 환영해요",
    "registered": "가입되었습니다",
    "failed": "완료하지 못했습니다. 다시 시도하세요.",
    "wechatError": "WeChat 로그인을 잠시 후 다시 시도하세요.",
    "wechatSuccess": "WeChat 로그인 완료",
    "linkError": "WeChat 연결을 잠시 후 다시 시도하세요.",
    "destination": "목적지 입력",
    "destinationHint": "도쿄, 뉴욕, 서울 등",
    "selected": "선택: ",
    "bali": "발리",
    "kyoto": "교토",
    "paris": "파리",
    "santorini": "산토리니",
    "indonesia": "인도네시아",
    "japan": "일본",
    "france": "프랑스",
    "greece": "그리스",
    "confirm": "확인",
    "cancel": "취소"
  },
  "id": {
    "hero": "Rencanakan perjalanan, bandingkan penginapan, hubungi driver lokal",
    "login": "Masuk",
    "register": "Daftar",
    "name": "Nama",
    "nameHint": "Nama Anda",
    "email": "Email",
    "code": "Kode email",
    "codeHint": "6 digit",
    "sendCode": "Kirim kode",
    "password": "Kata sandi",
    "passwordHint": "Minimal 6 karakter",
    "or": "atau",
    "wechatBusy": "Menghubungkan WeChat…",
    "wechatLogin": "Masuk dengan WeChat",
    "linkHint": "Sudah punya akun email? Masuk dengan email, lalu tautkan WeChat agar tidak membuat akun kedua.",
    "expiry": "Kode berlaku 10 menit. Kirim ulang setelah 60 detik.",
    "hello": "Halo, ",
    "where": "Mulai dari Bali: tempat nyata dan rute yang bisa langsung digunakan.",
    "other": "Masukkan tujuan lain…",
    "linkTitle": "Tautkan WeChat",
    "linkCopy": "Masuk lewat WeChat berikutnya. Akun lain tidak akan digabung.",
    "link": "Tautkan",
    "linked": "WeChat tertaut",
    "start": "Mulai di sini",
    "ask": "Tanya soal perjalanan",
    "advice": "Dapatkan saran praktis",
    "compare": "Bandingkan tiket & hotel",
    "options": "Jelajahi pilihan",
    "trips": "Perjalanan saya",
    "continue": "Lanjutkan rencana",
    "prefs": "Preferensi perjalanan",
    "habits": "Simpan kesukaan Anda",
    "moments": "Momen dari pulau",
    "galleryCopy": "Jelajahi foto, tempat, dan tips perjalanan.",
    "gallery": "Lihat foto",
    "logout": "Keluar",
    "logoutAsk": "Keluar dari akun ini?",
    "validEmail": "Isi email yang valid terlebih dahulu",
    "codeSent": "Kode terkirim",
    "codeFailed": "Kode gagal dikirim. Coba lagi.",
    "required": "Isi email dan kata sandi",
    "passwordShort": "Kata sandi minimal 6 karakter",
    "nameRequired": "Isi nama Anda",
    "codeRequired": "Isi kode email 6 digit",
    "welcome": "Selamat datang kembali",
    "registered": "Akun dibuat",
    "failed": "Belum berhasil. Coba lagi.",
    "wechatError": "Login WeChat belum tersedia. Coba lagi nanti.",
    "wechatSuccess": "Berhasil masuk lewat WeChat",
    "linkError": "WeChat belum dapat ditautkan. Coba lagi nanti.",
    "destination": "Masukkan tujuan",
    "destinationHint": "Tokyo, New York, Seoul…",
    "selected": "Dipilih: ",
    "bali": "Bali",
    "kyoto": "Kyoto",
    "paris": "Paris",
    "santorini": "Santorini",
    "indonesia": "Indonesia",
    "japan": "Jepang",
    "france": "Prancis",
    "greece": "Yunani",
    "confirm": "OK",
    "cancel": "Batal"
  }
};
