module.exports = {
  "zh": {
    "title": "我的",
    "signedOut": "尚未登录",
    "login": "前往登录",
    "prefs": "旅行偏好",
    "set": "已设置",
    "unset": "未设置",
    "history": "对话历史",
    "language": "语言 / Language",
    "website": "复制网站链接",
    "about": "关于 WanderMind",
    "logout": "退出登录",
    "logoutAsk": "确定退出当前账号吗？",
    "loggedOut": "已退出",
    "copied": "网址已复制",
    "copyFailed": "复制失败，请重试",
    "loginFirst": "请先登录",
    "prefsLogin": "登录后可保存旅行偏好",
    "aboutCopy": "规划行程、浏览 Bali 路线，并通过平台联系当地司机。\nwandermind.cc · v1.0.0",
    "confirm": "确定",
    "cancel": "取消"
  },
  "en": {
    "title": "My account",
    "signedOut": "Not signed in",
    "login": "Sign in",
    "prefs": "Travel preferences",
    "set": "Saved",
    "unset": "Not set",
    "history": "Chat history",
    "language": "Language",
    "website": "Copy website link",
    "about": "About WanderMind",
    "logout": "Sign out",
    "logoutAsk": "Sign out of this account?",
    "loggedOut": "Signed out",
    "copied": "Link copied",
    "copyFailed": "Could not copy. Try again.",
    "loginFirst": "Sign in first",
    "prefsLogin": "Sign in to save travel preferences",
    "aboutCopy": "Plan trips, explore Bali routes and contact local drivers through WanderMind.\nwandermind.cc · v1.0.0",
    "confirm": "OK",
    "cancel": "Cancel"
  },
  "ja": {
    "title": "マイページ",
    "signedOut": "ログインしていません",
    "login": "ログイン",
    "prefs": "旅行の好み",
    "set": "保存済み",
    "unset": "未設定",
    "history": "チャット履歴",
    "language": "言語 / Language",
    "website": "サイトのリンクをコピー",
    "about": "WanderMindについて",
    "logout": "ログアウト",
    "logoutAsk": "このアカウントからログアウトしますか？",
    "loggedOut": "ログアウトしました",
    "copied": "リンクをコピーしました",
    "copyFailed": "コピーできませんでした。再試行してください。",
    "loginFirst": "ログインしてください",
    "prefsLogin": "旅行の好みを保存するにはログインしてください",
    "aboutCopy": "旅行を計画し、バリのルートを探し、WanderMindを通じて地元のドライバーに相談できます。\nwandermind.cc · v1.0.0",
    "confirm": "OK",
    "cancel": "キャンセル"
  },
  "ko": {
    "title": "내 계정",
    "signedOut": "로그인하지 않았습니다",
    "login": "로그인",
    "prefs": "여행 취향",
    "set": "저장됨",
    "unset": "미설정",
    "history": "대화 기록",
    "language": "언어 / Language",
    "website": "웹사이트 링크 복사",
    "about": "WanderMind 소개",
    "logout": "로그아웃",
    "logoutAsk": "이 계정에서 로그아웃할까요?",
    "loggedOut": "로그아웃되었습니다",
    "copied": "링크가 복사되었습니다",
    "copyFailed": "복사하지 못했습니다. 다시 시도하세요.",
    "loginFirst": "먼저 로그인하세요",
    "prefsLogin": "여행 취향을 저장하려면 로그인하세요",
    "aboutCopy": "여행을 계획하고 발리 경로를 둘러보며 WanderMind를 통해 현지 기사에게 문의하세요.\nwandermind.cc · v1.0.0",
    "confirm": "확인",
    "cancel": "취소"
  },
  "id": {
    "title": "Akun saya",
    "signedOut": "Belum masuk",
    "login": "Masuk",
    "prefs": "Preferensi perjalanan",
    "set": "Tersimpan",
    "unset": "Belum diatur",
    "history": "Riwayat chat",
    "language": "Bahasa / Language",
    "website": "Salin tautan situs",
    "about": "Tentang WanderMind",
    "logout": "Keluar",
    "logoutAsk": "Keluar dari akun ini?",
    "loggedOut": "Sudah keluar",
    "copied": "Tautan disalin",
    "copyFailed": "Gagal menyalin. Coba lagi.",
    "loginFirst": "Masuk terlebih dahulu",
    "prefsLogin": "Masuk untuk menyimpan preferensi perjalanan",
    "aboutCopy": "Rencanakan perjalanan, jelajahi rute Bali, dan hubungi driver lokal melalui WanderMind.\nwandermind.cc · v1.0.0",
    "confirm": "OK",
    "cancel": "Batal"
  }
};
