module.exports = {
  "zh": {
    "advisor": "旅行顾问",
    "fast": "快速",
    "deep": "深入",
    "fastLabel": "快速回答",
    "deepLabel": "深入规划",
    "welcome": "从一个具体问题开始",
    "hint": "路线、交通、住宿与当地体验",
    "searched": "已检索在线信息",
    "retry": "重试刚才的问题",
    "input": "输入你的旅行问题…",
    "send": "发送",
    "restoreFailed": "对话恢复失败",
    "custom": "自定义",
    "fastToast": "已切换到快速回答",
    "deepToast": "已切换到深入规划",
    "login": "请先登录",
    "loginHint": "登录后即可开始对话",
    "safety": "内容安全校验暂不可用，请稍后重试",
    "sendFailed": "暂时无法发送",
    "noReply": "AI 没有返回内容，请重试",
    "syncFailed": "回复已保存在本机；云端同步失败，可继续使用。",
    "error": "出了点问题",
    "tryAgain": "请稍后重试",
    "kept": "输入内容已保留。",
    "confirm": "确定",
    "stay": "推荐适合住三晚的区域",
    "route": "安排一条少绕路的一日路线",
    "food": "推荐当地餐厅与特色菜",
    "budget": "估算两个人七天的旅行预算"
  },
  "en": {
    "advisor": "Travel advisor",
    "fast": "Quick",
    "deep": "Detailed",
    "fastLabel": "Quick answer",
    "deepLabel": "Detailed planning",
    "welcome": "Start with one question",
    "hint": "Routes, transport, stays and local experiences",
    "searched": "Online sources searched",
    "retry": "Retry your question",
    "input": "Ask a travel question…",
    "send": "Send",
    "restoreFailed": "Could not restore chat",
    "custom": "Custom",
    "fastToast": "Quick answers selected",
    "deepToast": "Detailed planning selected",
    "login": "Sign in first",
    "loginHint": "Sign in to start a chat",
    "safety": "Content check unavailable. Try again later.",
    "sendFailed": "Could not send",
    "noReply": "No reply received. Try again.",
    "syncFailed": "Saved on this device. Cloud sync failed; you can keep chatting.",
    "error": "Something went wrong",
    "tryAgain": "Please try again later",
    "kept": "Your input was kept.",
    "confirm": "OK",
    "stay": "Where should I stay for three nights?",
    "route": "Plan a day with less backtracking",
    "food": "Suggest local restaurants and dishes",
    "budget": "Estimate a seven-day budget for two"
  },
  "ja": {
    "advisor": "旅行相談",
    "fast": "クイック",
    "deep": "詳しく",
    "fastLabel": "簡潔な回答",
    "deepLabel": "詳しい計画",
    "welcome": "気になることから聞いてみましょう",
    "hint": "ルート・交通・宿泊・現地体験",
    "searched": "オンライン情報を検索済み",
    "retry": "質問を再送",
    "input": "旅行について質問…",
    "send": "送信",
    "restoreFailed": "会話を復元できませんでした",
    "custom": "自由入力",
    "fastToast": "簡潔な回答に切り替えました",
    "deepToast": "詳しい計画に切り替えました",
    "login": "ログインしてください",
    "loginHint": "ログインして会話を始めましょう",
    "safety": "内容確認を利用できません。後でお試しください",
    "sendFailed": "送信できませんでした",
    "noReply": "回答がありません。再試行してください",
    "syncFailed": "端末に保存済み。クラウド同期に失敗しましたが会話は続けられます。",
    "error": "エラーが発生しました",
    "tryAgain": "後でお試しください",
    "kept": "入力内容は保持されています。",
    "confirm": "確認",
    "stay": "3泊するならどのエリアがおすすめ？",
    "route": "移動の無駄が少ない1日ルートを考えて",
    "food": "地元の料理とレストランを教えて",
    "budget": "2人で7日間の予算を見積もって"
  },
  "ko": {
    "advisor": "여행 상담",
    "fast": "빠르게",
    "deep": "자세히",
    "fastLabel": "빠른 답변",
    "deepLabel": "자세한 계획",
    "welcome": "궁금한 것부터 물어보세요",
    "hint": "경로, 교통, 숙소와 현지 체험",
    "searched": "온라인 정보 검색됨",
    "retry": "질문 다시 보내기",
    "input": "여행 질문을 입력하세요…",
    "send": "보내기",
    "restoreFailed": "대화 복원 실패",
    "custom": "직접 입력",
    "fastToast": "빠른 답변으로 변경했어요",
    "deepToast": "자세한 계획으로 변경했어요",
    "login": "먼저 로그인하세요",
    "loginHint": "로그인하고 대화를 시작하세요",
    "safety": "내용 확인을 사용할 수 없어요. 나중에 다시 시도하세요",
    "sendFailed": "보낼 수 없어요",
    "noReply": "답변이 없어요. 다시 시도하세요",
    "syncFailed": "기기에 저장했어요. 클라우드 동기화에 실패했지만 계속 대화할 수 있어요.",
    "error": "문제가 생겼어요",
    "tryAgain": "나중에 다시 시도하세요",
    "kept": "입력 내용은 보관했어요.",
    "confirm": "확인",
    "stay": "3박하기 좋은 지역은 어디인가요?",
    "route": "이동을 줄이는 하루 경로를 짜 주세요",
    "food": "현지 식당과 음식을 추천해 주세요",
    "budget": "2인 7일 여행 예산을 알려 주세요"
  },
  "id": {
    "advisor": "Penasihat perjalanan",
    "fast": "Cepat",
    "deep": "Terperinci",
    "fastLabel": "Jawaban singkat",
    "deepLabel": "Rencana terperinci",
    "welcome": "Mulai dengan satu pertanyaan",
    "hint": "Rute, transportasi, penginapan, dan pengalaman lokal",
    "searched": "Sumber online ditelusuri",
    "retry": "Coba pertanyaan lagi",
    "input": "Tanyakan tentang perjalanan…",
    "send": "Kirim",
    "restoreFailed": "Gagal memulihkan percakapan",
    "custom": "Pilihan sendiri",
    "fastToast": "Jawaban singkat dipilih",
    "deepToast": "Rencana terperinci dipilih",
    "login": "Masuk dahulu",
    "loginHint": "Masuk untuk memulai percakapan",
    "safety": "Pemeriksaan konten belum tersedia. Coba nanti.",
    "sendFailed": "Belum dapat mengirim",
    "noReply": "Belum ada jawaban. Coba lagi.",
    "syncFailed": "Tersimpan di perangkat. Sinkronisasi cloud gagal; Anda bisa lanjut.",
    "error": "Ada kendala",
    "tryAgain": "Coba lagi nanti",
    "kept": "Input Anda tetap tersimpan.",
    "confirm": "OK",
    "stay": "Area mana yang cocok untuk menginap tiga malam?",
    "route": "Susun rute sehari tanpa banyak bolak-balik",
    "food": "Rekomendasikan restoran dan makanan lokal",
    "budget": "Perkirakan anggaran tujuh hari untuk dua orang"
  }
};
