module.exports = {
  "zh": {
    "title": "景点很分散，路线不该绕",
    "subtitle": "先完整浏览 6 条公共路线，再按日期、节奏与预算匹配你的专业路线。",
    "match": "匹配我的路线",
    "diy": "AI 自助规划",
    "personal": "个性化专业路线",
    "unlocked": "已解锁",
    "preview": "约 70% 预览",
    "day": "第",
    "photos": "看景色",
    "unlock": "复制网页解锁链接",
    "driver": "联系当地司机",
    "remaining": "同一行程剩余调整次数：",
    "price": "¥9.9 或 30 积分解锁，含 3 次同行程调整",
    "free": "6 条公共路线 · 全部免费",
    "gallery": "看岛屿作品集",
    "hint": "点开景点名称，可查看不同景色与介绍",
    "loading": "正在读取路线…",
    "retry": "重试",
    "recommended": "推荐天数：",
    "use": "按这条路线匹配我的行程",
    "failed": "路线加载失败",
    "login": "请先登录",
    "loginCopy": "登录后可保存预览，并在网页与小程序间恢复路线。",
    "copied": "解锁链接已复制",
    "copyFailed": "复制失败，请重试",
    "ok": "确定"
  },
  "en": {
    "title": "Bali is spread out. Your route should flow.",
    "subtitle": "Explore 6 free routes, then match a personal route to your dates, pace and budget.",
    "match": "Match my route",
    "diy": "Plan with AI",
    "personal": "Personal professional route",
    "unlocked": "Unlocked",
    "preview": "About 70% preview",
    "day": "Day",
    "photos": "See photos",
    "unlock": "Copy link to unlock on web",
    "driver": "Contact a local driver",
    "remaining": "Adjustments left for this trip: ",
    "price": "Unlock for CNY 9.9 or 30 points, with 3 adjustments to this trip.",
    "free": "6 public routes · All free",
    "gallery": "Explore island photos",
    "hint": "Tap a place to see photos and details.",
    "loading": "Loading routes…",
    "retry": "Retry",
    "recommended": "Recommended days: ",
    "use": "Match my trip to this route",
    "failed": "Could not load routes",
    "login": "Sign in first",
    "loginCopy": "Sign in to save your preview and use it on web or Mini Program.",
    "copied": "Unlock link copied",
    "copyFailed": "Could not copy. Retry.",
    "ok": "OK"
  },
  "ja": {
    "title": "点在する名所を、無駄のないルートで",
    "subtitle": "無料の6ルートを見比べて、日程・ペース・予算に合う旅へ。",
    "match": "ルートを選ぶ",
    "diy": "AIで計画",
    "personal": "あなたに合わせた専門ルート",
    "unlocked": "解除済み",
    "preview": "約70%プレビュー",
    "day": "日程",
    "photos": "写真を見る",
    "unlock": "Web解除リンクをコピー",
    "driver": "地元ドライバーに相談",
    "remaining": "この旅行の残り調整回数：",
    "price": "CNY 9.9または30ポイントで解除。同じ旅行の調整3回を含みます。",
    "free": "6つの公開ルート・すべて無料",
    "gallery": "島の写真を見る",
    "hint": "場所をタップして写真と紹介を見る",
    "loading": "ルートを読み込み中…",
    "retry": "再試行",
    "recommended": "おすすめ日数：",
    "use": "このルートで旅を計画",
    "failed": "ルートを読み込めませんでした",
    "login": "ログインしてください",
    "loginCopy": "ログインしてプレビューを保存し、Webとミニプログラムで続けられます。",
    "copied": "解除リンクをコピーしました",
    "copyFailed": "コピーできませんでした。再試行してください。",
    "ok": "OK"
  },
  "ko": {
    "title": "흩어진 명소도 편한 동선으로",
    "subtitle": "무료 경로 6개를 비교하고 날짜·속도·예산에 맞춰 추천받으세요.",
    "match": "내 경로 추천",
    "diy": "AI로 계획",
    "personal": "맞춤 전문 경로",
    "unlocked": "잠금 해제됨",
    "preview": "약 70% 미리보기",
    "day": "일차",
    "photos": "사진 보기",
    "unlock": "웹 잠금 해제 링크 복사",
    "driver": "현지 기사 문의",
    "remaining": "같은 여행의 남은 수정 횟수: ",
    "price": "CNY 9.9 또는 30포인트로 해제하며 같은 여행 수정 3회가 포함됩니다.",
    "free": "공개 경로 6개 · 모두 무료",
    "gallery": "섬 사진 둘러보기",
    "hint": "장소를 눌러 사진과 설명을 확인하세요",
    "loading": "경로 불러오는 중…",
    "retry": "다시 시도",
    "recommended": "추천 일수: ",
    "use": "이 경로로 여행 추천",
    "failed": "경로를 불러오지 못했습니다",
    "login": "먼저 로그인하세요",
    "loginCopy": "로그인하면 미리보기를 저장하고 웹과 미니프로그램에서 이어갈 수 있습니다.",
    "copied": "잠금 해제 링크 복사됨",
    "copyFailed": "복사하지 못했습니다. 다시 시도하세요.",
    "ok": "확인"
  },
  "id": {
    "title": "Tempatnya tersebar, rutenya tetap searah",
    "subtitle": "Lihat 6 rute gratis, lalu sesuaikan dengan tanggal, ritme, dan anggaran.",
    "match": "Cocokkan rute saya",
    "diy": "Rencanakan dengan AI",
    "personal": "Rute profesional personal",
    "unlocked": "Terbuka",
    "preview": "Pratinjau sekitar 70%",
    "day": "Hari",
    "photos": "Lihat foto",
    "unlock": "Salin tautan untuk buka di web",
    "driver": "Hubungi driver lokal",
    "remaining": "Sisa penyesuaian perjalanan ini: ",
    "price": "Buka dengan CNY 9.9 atau 30 poin, termasuk 3 penyesuaian perjalanan ini.",
    "free": "6 rute publik · Semua gratis",
    "gallery": "Lihat foto pulau",
    "hint": "Ketuk tempat untuk melihat foto dan detail.",
    "loading": "Memuat rute…",
    "retry": "Coba lagi",
    "recommended": "Saran jumlah hari: ",
    "use": "Sesuaikan perjalanan dengan rute ini",
    "failed": "Rute gagal dimuat",
    "login": "Masuk terlebih dahulu",
    "loginCopy": "Masuk untuk menyimpan pratinjau dan melanjutkan di web atau Mini Program.",
    "copied": "Tautan buka disalin",
    "copyFailed": "Gagal menyalin. Coba lagi.",
    "ok": "OK"
  }
};
