module.exports = {
  "zh": {
    "title": "旅行偏好",
    "intro": "记下你的旅行偏好",
    "hint": "预算、同行方式与特殊需求会用于后续建议，你可以随时修改",
    "budgetTitle": "预算档次",
    "budget": "经济实惠",
    "midrange": "标准舒适",
    "luxury": "豪华享受",
    "styleTitle": "旅行风格",
    "multi": "可多选",
    "culture": "文化历史",
    "food": "美食探索",
    "adventure": "冒险户外",
    "relax": "悠闲放松",
    "nature": "自然风光",
    "wellness": "养生健康",
    "partyTitle": "同行方式",
    "solo": "独自旅行",
    "couple": "情侣出行",
    "family": "家庭亲子",
    "group": "朋友/团体",
    "notesTitle": "特殊偏好与备注",
    "notesHint": "如：素食、无障碍设施、食物过敏…",
    "clear": "清除全部",
    "saving": "正在保存…",
    "save": "保存旅行偏好",
    "savedHint": "已保存。后续规划会参考这些偏好。",
    "login": "请先登录",
    "loginHint": "登录后即可保存偏好",
    "saved": "偏好已保存",
    "failed": "保存失败，请重试",
    "clearTitle": "清除偏好",
    "clearAsk": "确定清除已保存的旅行偏好吗？",
    "cleared": "已清除",
    "cancel": "取消",
    "confirm": "确定"
  },
  "en": {
    "title": "Travel preferences",
    "intro": "Save your travel preferences",
    "hint": "Budget, companions and special needs help shape suggestions. You can change these anytime.",
    "budgetTitle": "Budget",
    "budget": "Budget-friendly",
    "midrange": "Comfort",
    "luxury": "Luxury",
    "styleTitle": "Travel style",
    "multi": "Choose several",
    "culture": "Culture & history",
    "food": "Food",
    "adventure": "Outdoors",
    "relax": "Relaxation",
    "nature": "Nature",
    "wellness": "Wellness",
    "partyTitle": "Travelling with",
    "solo": "Solo",
    "couple": "Partner",
    "family": "Family",
    "group": "Friends / group",
    "notesTitle": "Special requests",
    "notesHint": "e.g. vegetarian food, accessibility, food allergies…",
    "clear": "Clear all",
    "saving": "Saving…",
    "save": "Save preferences",
    "savedHint": "Saved. Future plans will use these preferences.",
    "login": "Sign in first",
    "loginHint": "Sign in to save preferences",
    "saved": "Preferences saved",
    "failed": "Could not save. Try again.",
    "clearTitle": "Clear preferences",
    "clearAsk": "Clear your saved travel preferences?",
    "cleared": "Cleared",
    "cancel": "Cancel",
    "confirm": "OK"
  },
  "ja": {
    "title": "旅の好み",
    "intro": "旅の好みを保存",
    "hint": "予算、同行者、希望を今後の提案に活用します。いつでも変更できます。",
    "budgetTitle": "予算",
    "budget": "節約重視",
    "midrange": "快適さ重視",
    "luxury": "ラグジュアリー",
    "styleTitle": "旅のスタイル",
    "multi": "複数選択可",
    "culture": "文化・歴史",
    "food": "グルメ",
    "adventure": "アウトドア",
    "relax": "リラックス",
    "nature": "自然",
    "wellness": "ウェルネス",
    "partyTitle": "同行者",
    "solo": "一人旅",
    "couple": "パートナー",
    "family": "家族",
    "group": "友人・グループ",
    "notesTitle": "希望・補足",
    "notesHint": "例：ベジタリアン、バリアフリー、食物アレルギー…",
    "clear": "すべてクリア",
    "saving": "保存中…",
    "save": "好みを保存",
    "savedHint": "保存しました。今後の提案に反映します。",
    "login": "ログインしてください",
    "loginHint": "好みの保存にはログインが必要です",
    "saved": "保存しました",
    "failed": "保存できませんでした。再試行してください",
    "clearTitle": "好みをクリア",
    "clearAsk": "保存した旅の好みをクリアしますか？",
    "cleared": "クリアしました",
    "cancel": "キャンセル",
    "confirm": "確認"
  },
  "ko": {
    "title": "여행 취향",
    "intro": "여행 취향을 알려 주세요",
    "hint": "예산, 동행인과 요청 사항을 추천에 반영합니다. 언제든 바꿀 수 있어요.",
    "budgetTitle": "예산",
    "budget": "실속형",
    "midrange": "편안함",
    "luxury": "럭셔리",
    "styleTitle": "여행 스타일",
    "multi": "여러 개 선택 가능",
    "culture": "문화·역사",
    "food": "음식",
    "adventure": "야외 활동",
    "relax": "휴식",
    "nature": "자연",
    "wellness": "웰니스",
    "partyTitle": "동행인",
    "solo": "혼자",
    "couple": "연인",
    "family": "가족",
    "group": "친구·단체",
    "notesTitle": "요청 사항",
    "notesHint": "예: 채식, 접근성, 음식 알레르기…",
    "clear": "모두 지우기",
    "saving": "저장 중…",
    "save": "취향 저장",
    "savedHint": "저장했어요. 다음 계획에 반영합니다.",
    "login": "먼저 로그인하세요",
    "loginHint": "취향을 저장하려면 로그인하세요",
    "saved": "취향을 저장했어요",
    "failed": "저장하지 못했어요. 다시 시도하세요",
    "clearTitle": "취향 지우기",
    "clearAsk": "저장한 여행 취향을 지울까요?",
    "cleared": "지웠어요",
    "cancel": "취소",
    "confirm": "확인"
  },
  "id": {
    "title": "Preferensi perjalanan",
    "intro": "Simpan preferensi Anda",
    "hint": "Anggaran, teman perjalanan, dan kebutuhan khusus membantu saran berikutnya. Bisa diubah kapan saja.",
    "budgetTitle": "Anggaran",
    "budget": "Hemat",
    "midrange": "Nyaman",
    "luxury": "Mewah",
    "styleTitle": "Gaya perjalanan",
    "multi": "Boleh pilih beberapa",
    "culture": "Budaya & sejarah",
    "food": "Kuliner",
    "adventure": "Petualangan",
    "relax": "Santai",
    "nature": "Alam",
    "wellness": "Kebugaran",
    "partyTitle": "Teman perjalanan",
    "solo": "Sendiri",
    "couple": "Pasangan",
    "family": "Keluarga",
    "group": "Teman / rombongan",
    "notesTitle": "Kebutuhan khusus",
    "notesHint": "mis. vegetarian, aksesibilitas, alergi makanan…",
    "clear": "Hapus semua",
    "saving": "Menyimpan…",
    "save": "Simpan preferensi",
    "savedHint": "Tersimpan. Rencana berikutnya akan memakai preferensi ini.",
    "login": "Masuk dahulu",
    "loginHint": "Masuk untuk menyimpan preferensi",
    "saved": "Preferensi tersimpan",
    "failed": "Gagal menyimpan. Coba lagi.",
    "clearTitle": "Hapus preferensi",
    "clearAsk": "Hapus preferensi perjalanan yang tersimpan?",
    "cleared": "Dihapus",
    "cancel": "Batal",
    "confirm": "OK"
  }
};
