module.exports = {
  "zh": {
    "title": "酒店与机票",
    "hint": "复制链接后在浏览器预订，价格以预订平台为准",
    "hotels": "酒店",
    "flights": "机票",
    "area": "住宿区域",
    "all": "全部",
    "checkIn": "入住",
    "checkOut": "退房",
    "people": "人数",
    "person": "人",
    "searching": "正在查询…",
    "searchHotels": "查看酒店选择",
    "searchFlights": "查看机票选择",
    "reviews": "条评价",
    "rating": "评分",
    "priceUnknown": "价格待定",
    "night": "晚",
    "copyBooking": "点按复制预订链接",
    "emptyHotels": "暂无结果，请更换日期重试",
    "emptyFlights": "暂无航班，请更换日期或机场重试",
    "round": "往返",
    "oneway": "单程",
    "origin": "出发城市",
    "other": "其他城市",
    "selected": "已选：",
    "depart": "起飞",
    "returnDate": "返回",
    "copyFlights": "复制 Google Flights 链接",
    "custom": "自定义",
    "customTitle": "其他出发城市",
    "customHint": "输入城市名或 IATA 代码",
    "datesRequired": "请选择日期",
    "checkoutInvalid": "退房日期必须晚于入住",
    "failed": "搜索失败",
    "copied": "链接已复制，去浏览器打开",
    "copyFailed": "复制失败，请重试",
    "missingLink": "暂时没有预订链接",
    "originRequired": "请选择出发城市",
    "departRequired": "请选择起飞日期",
    "returnInvalid": "返回日期必须晚于起飞",
    "direct": "直飞",
    "stops": "次中转",
    "login": "请先登录",
    "loginHint": "登录后即可查询酒店与机票",
    "confirm": "确定",
    "cancel": "取消"
  },
  "en": {
    "title": "Hotels & flights",
    "hint": "Copy a link to book in your browser. Check final prices on the booking site.",
    "hotels": "Hotels",
    "flights": "Flights",
    "area": "Hotel area",
    "all": "All",
    "checkIn": "Check-in",
    "checkOut": "Check-out",
    "people": "Travellers",
    "person": "people",
    "searching": "Searching…",
    "searchHotels": "Find hotels",
    "searchFlights": "Find flights",
    "reviews": "reviews",
    "rating": "Rating",
    "priceUnknown": "Price unavailable",
    "night": "night",
    "copyBooking": "Tap to copy booking link",
    "emptyHotels": "No hotels found. Try different dates.",
    "emptyFlights": "No flights found. Try other dates or airports.",
    "round": "Return",
    "oneway": "One way",
    "origin": "Departure city",
    "other": "Other city",
    "selected": "Selected:",
    "depart": "Departure",
    "returnDate": "Return date",
    "copyFlights": "Copy Google Flights link",
    "custom": "Custom",
    "customTitle": "Other departure city",
    "customHint": "Enter a city or IATA code",
    "datesRequired": "Choose dates",
    "checkoutInvalid": "Check-out must follow check-in",
    "failed": "Search failed",
    "copied": "Link copied. Open it in your browser.",
    "copyFailed": "Could not copy. Try again.",
    "missingLink": "Booking link unavailable",
    "originRequired": "Choose a departure city",
    "departRequired": "Choose a departure date",
    "returnInvalid": "Return must follow departure",
    "direct": "Nonstop",
    "stops": "stops",
    "login": "Sign in first",
    "loginHint": "Sign in to find hotels and flights",
    "confirm": "OK",
    "cancel": "Cancel"
  },
  "ja": {
    "title": "ホテル・航空券",
    "hint": "リンクをコピーしてブラウザーで予約。料金は予約先で確認してください。",
    "hotels": "ホテル",
    "flights": "航空券",
    "area": "宿泊エリア",
    "all": "すべて",
    "checkIn": "チェックイン",
    "checkOut": "チェックアウト",
    "people": "人数",
    "person": "人",
    "searching": "検索中…",
    "searchHotels": "ホテルを探す",
    "searchFlights": "航空券を探す",
    "reviews": "件の口コミ",
    "rating": "評価",
    "priceUnknown": "料金未確認",
    "night": "泊",
    "copyBooking": "タップして予約リンクをコピー",
    "emptyHotels": "該当なし。日程を変えてお試しください",
    "emptyFlights": "便が見つかりません。日程や空港を変えてください",
    "round": "往復",
    "oneway": "片道",
    "origin": "出発都市",
    "other": "他の都市",
    "selected": "選択中：",
    "depart": "出発",
    "returnDate": "復路",
    "copyFlights": "Google Flightsリンクをコピー",
    "custom": "自由入力",
    "customTitle": "他の出発都市",
    "customHint": "都市名またはIATAコード",
    "datesRequired": "日程を選んでください",
    "checkoutInvalid": "チェックアウトはチェックインより後にしてください",
    "failed": "検索できませんでした",
    "copied": "コピーしました。ブラウザーで開いてください",
    "copyFailed": "コピーできませんでした",
    "missingLink": "予約リンクがありません",
    "originRequired": "出発都市を選んでください",
    "departRequired": "出発日を選んでください",
    "returnInvalid": "復路は出発日より後にしてください",
    "direct": "直行",
    "stops": "回乗継",
    "login": "ログインしてください",
    "loginHint": "ホテル・航空券検索にはログインしてください",
    "confirm": "確認",
    "cancel": "キャンセル"
  },
  "ko": {
    "title": "호텔·항공편",
    "hint": "링크를 복사해 브라우저에서 예약하세요. 최종 요금은 예약 사이트에서 확인하세요.",
    "hotels": "호텔",
    "flights": "항공편",
    "area": "숙박 지역",
    "all": "전체",
    "checkIn": "체크인",
    "checkOut": "체크아웃",
    "people": "인원",
    "person": "명",
    "searching": "검색 중…",
    "searchHotels": "호텔 찾기",
    "searchFlights": "항공편 찾기",
    "reviews": "개 후기",
    "rating": "평점",
    "priceUnknown": "요금 미확인",
    "night": "박",
    "copyBooking": "눌러서 예약 링크 복사",
    "emptyHotels": "결과가 없어요. 날짜를 바꿔 보세요",
    "emptyFlights": "항공편이 없어요. 날짜나 공항을 바꿔 보세요",
    "round": "왕복",
    "oneway": "편도",
    "origin": "출발 도시",
    "other": "다른 도시",
    "selected": "선택:",
    "depart": "출발",
    "returnDate": "귀국일",
    "copyFlights": "Google Flights 링크 복사",
    "custom": "직접 입력",
    "customTitle": "다른 출발 도시",
    "customHint": "도시 이름 또는 IATA 코드",
    "datesRequired": "날짜를 선택하세요",
    "checkoutInvalid": "체크아웃은 체크인 이후여야 해요",
    "failed": "검색 실패",
    "copied": "복사했어요. 브라우저에서 여세요",
    "copyFailed": "복사 실패. 다시 시도하세요",
    "missingLink": "예약 링크가 없어요",
    "originRequired": "출발 도시를 선택하세요",
    "departRequired": "출발일을 선택하세요",
    "returnInvalid": "귀국일은 출발일 이후여야 해요",
    "direct": "직항",
    "stops": "회 경유",
    "login": "먼저 로그인하세요",
    "loginHint": "호텔과 항공편 검색은 로그인 후 이용하세요",
    "confirm": "확인",
    "cancel": "취소"
  },
  "id": {
    "title": "Hotel & penerbangan",
    "hint": "Salin tautan untuk memesan lewat browser. Harga akhir mengikuti situs pemesanan.",
    "hotels": "Hotel",
    "flights": "Penerbangan",
    "area": "Area menginap",
    "all": "Semua",
    "checkIn": "Check-in",
    "checkOut": "Check-out",
    "people": "Jumlah tamu",
    "person": "orang",
    "searching": "Mencari…",
    "searchHotels": "Cari hotel",
    "searchFlights": "Cari penerbangan",
    "reviews": "ulasan",
    "rating": "Nilai",
    "priceUnknown": "Harga belum tersedia",
    "night": "malam",
    "copyBooking": "Ketuk untuk menyalin tautan",
    "emptyHotels": "Tidak ada hasil. Coba tanggal lain.",
    "emptyFlights": "Tidak ada penerbangan. Coba tanggal atau bandara lain.",
    "round": "Pulang-pergi",
    "oneway": "Sekali jalan",
    "origin": "Kota asal",
    "other": "Kota lain",
    "selected": "Dipilih:",
    "depart": "Berangkat",
    "returnDate": "Kembali",
    "copyFlights": "Salin tautan Google Flights",
    "custom": "Pilihan sendiri",
    "customTitle": "Kota asal lain",
    "customHint": "Nama kota atau kode IATA",
    "datesRequired": "Pilih tanggal",
    "checkoutInvalid": "Check-out harus setelah check-in",
    "failed": "Pencarian gagal",
    "copied": "Tautan disalin. Buka di browser.",
    "copyFailed": "Gagal menyalin. Coba lagi.",
    "missingLink": "Tautan pemesanan belum tersedia",
    "originRequired": "Pilih kota asal",
    "departRequired": "Pilih tanggal berangkat",
    "returnInvalid": "Tanggal kembali harus setelah berangkat",
    "direct": "Langsung",
    "stops": "transit",
    "login": "Masuk dahulu",
    "loginHint": "Masuk untuk mencari hotel dan penerbangan",
    "confirm": "OK",
    "cancel": "Batal"
  }
};
