// Labels only: API IDs and CNY budget values stay unchanged.
module.exports = {
  "zh": {
    "title": "先排出一条顺路的 Bali 行程",
    "subtitle": "根据 G1–G7 区域与 R1–R6 主题匹配。带 * 为必填。",
    "basic": "基本行程",
    "audience": "是否第一次去 Bali",
    "first": "第一次去",
    "returning": "去过 Bali",
    "departure": "出发日期",
    "returnDate": "返程日期",
    "people": "同行人数",
    "budget": "预算档位",
    "way": "旅行方式",
    "style": "行程风格",
    "comfort": "舒适平衡",
    "comfortCopy": "经典与松弛兼顾",
    "deep": "深度探索",
    "deepCopy": "更多文化与在地体验",
    "resort": "度假放松",
    "resortCopy": "少换酒店、留足空白",
    "pace": "行程节奏",
    "relaxed": "轻松",
    "balanced": "平衡",
    "active": "充实",
    "goals": "最关注什么",
    "limit": "最多选择 3 项",
    "local": "在地文化",
    "photo": "自然摄影",
    "hidden": "小众路线",
    "easy": "少做攻略",
    "value": "控制预算",
    "days": "天",
    "guests": "人",
    "selected": "项关注",
    "busy": "正在匹配适合你的路线…",
    "submit": "生成我的 Bali 路线",
    "benefit": "先预览约 70%；解锁完整路线后含 3 次同一行程调整",
    "invalidDates": "返程日期须晚于出发日期",
    "noGoals": "请至少选择一个关注点",
    "success": "路线已匹配",
    "failed": "匹配失败，请重试"
  },
  "en": {
    "title": "Plan a Bali trip that flows",
    "subtitle": "Matched across G1–G7 areas and R1–R6 themes. * Required.",
    "basic": "Trip basics",
    "audience": "First time in Bali?",
    "first": "First visit",
    "returning": "Been before",
    "departure": "Departure",
    "returnDate": "Return",
    "people": "Travellers",
    "budget": "Budget range",
    "way": "Your travel style",
    "style": "Trip style",
    "comfort": "Comfort",
    "comfortCopy": "Highlights with time to unwind",
    "deep": "Explore",
    "deepCopy": "Culture and local experiences",
    "resort": "Unwind",
    "resortCopy": "Fewer hotel moves, more free time",
    "pace": "Daily pace",
    "relaxed": "Easy",
    "balanced": "Balanced",
    "active": "Full",
    "goals": "What matters most?",
    "limit": "Choose up to 3",
    "local": "Local culture",
    "photo": "Nature & photos",
    "hidden": "Hidden gems",
    "easy": "Less planning",
    "value": "Stay on budget",
    "days": "days",
    "guests": "travellers",
    "selected": "interests",
    "busy": "Finding your route…",
    "submit": "Build my Bali route",
    "benefit": "Preview about 70%. Unlock the full route with 3 adjustments to this trip.",
    "invalidDates": "Return must be after departure",
    "noGoals": "Choose at least one interest",
    "success": "Route matched",
    "failed": "Could not match. Please retry."
  },
  "ja": {
    "title": "移動もスムーズなバリ旅行へ",
    "subtitle": "G1–G7 エリアと R1–R6 テーマから選びます。* は必須です。",
    "basic": "旅行の基本",
    "audience": "バリ島は初めてですか？",
    "first": "初めて",
    "returning": "訪問経験あり",
    "departure": "出発日",
    "returnDate": "帰着日",
    "people": "旅行人数",
    "budget": "予算の目安",
    "way": "旅の楽しみ方",
    "style": "旅行スタイル",
    "comfort": "快適に",
    "comfortCopy": "定番と休息をバランスよく",
    "deep": "深く知る",
    "deepCopy": "文化と地元の体験を満喫",
    "resort": "のんびり",
    "resortCopy": "ホテル移動を減らし自由時間を",
    "pace": "一日のペース",
    "relaxed": "ゆったり",
    "balanced": "バランス",
    "active": "充実",
    "goals": "重視すること",
    "limit": "3つまで選択",
    "local": "地元の文化",
    "photo": "自然と写真",
    "hidden": "穴場",
    "easy": "計画の手間を減らす",
    "value": "予算を抑える",
    "days": "日間",
    "guests": "人",
    "selected": "項目",
    "busy": "ルートを選んでいます…",
    "submit": "バリのルートを作成",
    "benefit": "約70%をプレビュー。解除後は全ルートと同じ旅行の調整3回が含まれます。",
    "invalidDates": "帰着日は出発日より後にしてください",
    "noGoals": "重視することを1つ以上選んでください",
    "success": "ルートが見つかりました",
    "failed": "失敗しました。もう一度お試しください。"
  },
  "ko": {
    "title": "동선이 편한 발리 여행",
    "subtitle": "G1–G7 지역과 R1–R6 테마로 추천합니다. * 필수 항목",
    "basic": "기본 일정",
    "audience": "발리 여행이 처음인가요?",
    "first": "처음이에요",
    "returning": "방문한 적 있어요",
    "departure": "출발일",
    "returnDate": "귀국일",
    "people": "여행 인원",
    "budget": "예산 범위",
    "way": "여행 방식",
    "style": "여행 스타일",
    "comfort": "편안하게",
    "comfortCopy": "명소와 휴식을 균형 있게",
    "deep": "깊이 탐험",
    "deepCopy": "문화와 현지 체험 중심",
    "resort": "여유롭게",
    "resortCopy": "숙소 이동은 적게, 자유 시간은 넉넉히",
    "pace": "하루 여행 속도",
    "relaxed": "여유",
    "balanced": "균형",
    "active": "알차게",
    "goals": "중요한 것은?",
    "limit": "최대 3개 선택",
    "local": "현지 문화",
    "photo": "자연과 사진",
    "hidden": "숨은 명소",
    "easy": "계획 부담 줄이기",
    "value": "예산 지키기",
    "days": "일",
    "guests": "명",
    "selected": "관심사",
    "busy": "맞는 경로를 찾고 있어요…",
    "submit": "나의 발리 경로 만들기",
    "benefit": "약 70% 미리보기. 전체 경로 잠금 해제 시 같은 여행의 수정 3회가 포함됩니다.",
    "invalidDates": "귀국일은 출발일 이후여야 합니다",
    "noGoals": "관심사를 하나 이상 선택하세요",
    "success": "경로를 찾았어요",
    "failed": "추천에 실패했습니다. 다시 시도하세요."
  },
  "id": {
    "title": "Rencanakan Bali dengan rute yang searah",
    "subtitle": "Dicocokkan dari area G1–G7 dan tema R1–R6. * Wajib diisi.",
    "basic": "Detail perjalanan",
    "audience": "Pertama kali ke Bali?",
    "first": "Pertama kali",
    "returning": "Pernah ke Bali",
    "departure": "Tanggal berangkat",
    "returnDate": "Tanggal pulang",
    "people": "Jumlah tamu",
    "budget": "Kisaran anggaran",
    "way": "Cara menikmati perjalanan",
    "style": "Gaya perjalanan",
    "comfort": "Nyaman",
    "comfortCopy": "Wisata utama dan waktu santai",
    "deep": "Eksplorasi",
    "deepCopy": "Budaya dan pengalaman lokal",
    "resort": "Santai",
    "resortCopy": "Minim pindah hotel, lebih banyak waktu luang",
    "pace": "Ritme harian",
    "relaxed": "Santai",
    "balanced": "Seimbang",
    "active": "Padat",
    "goals": "Apa yang paling penting?",
    "limit": "Pilih maksimal 3",
    "local": "Budaya lokal",
    "photo": "Alam & foto",
    "hidden": "Tempat tersembunyi",
    "easy": "Minim perencanaan",
    "value": "Hemat anggaran",
    "days": "hari",
    "guests": "tamu",
    "selected": "minat",
    "busy": "Mencari rute yang sesuai…",
    "submit": "Buat rute Bali saya",
    "benefit": "Pratinjau sekitar 70%. Buka rute lengkap dengan 3 penyesuaian untuk perjalanan ini.",
    "invalidDates": "Tanggal pulang harus setelah berangkat",
    "noGoals": "Pilih setidaknya satu minat",
    "success": "Rute ditemukan",
    "failed": "Rute belum ditemukan. Coba lagi."
  }
};
