// Public browsing snapshot only. Never bundle accounts, orders or entitlements.
const fs = require('node:fs'), path = require('node:path'), crypto = require('node:crypto');
const root = path.resolve(__dirname, '..');
const names = ['bali-travel-data', 'bali-extensions', 'bali-food', 'poi-media-catalog', 'image-publish-manifest'];
const imageFields = 'id sha256 source_sha256 title description alt_text place_name primary_theme category sub_category region region_ids area route_ids extension_ids album tags secondaryTags poi_ids web_url web_optimized_path image_url thumbnail_url thumbnail_path media_scope verification_status location_status display_priority rights approval_status publication_status'.split(' ');
function build() {
  const catalogs = {}, hashes = {};
  for (const name of names) {
    const value = JSON.parse(fs.readFileSync(path.join(root, 'wandermind-studio/frontend/assets/data', name + '.json'), 'utf8'));
    hashes[name] = crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
    if (name === 'image-publish-manifest' || name === 'poi-media-catalog') {
      // First paint uses alt/title; full descriptions arrive in the live catalog.
      catalogs[name] = { images: value.images.map(item => Object.fromEntries(imageFields.filter(key => key !== 'description' && item[key] !== undefined).map(key => [key, item[key]]))) };
    } else catalogs[name] = value;
  }
  return '// Generated by tools/build_miniprogram_catalog.cjs --write. Public facts; refresh source before release.\nmodule.exports = ' + JSON.stringify({ hashes, catalogs }) + ';\n';
}
if (require.main === module) {
  const output = path.join(root, 'miniprogram/utils/public-catalog-seed.js'), expected = build();
  if (process.argv.includes('--write')) fs.writeFileSync(output, expected);
  else if (!fs.existsSync(output) || fs.readFileSync(output, 'utf8') !== expected) throw new Error('Public catalog snapshot drift: run node tools/build_miniprogram_catalog.cjs --write');
  console.log('Public catalog snapshot: ' + Buffer.byteLength(expected) + ' bytes; source parity checked');
}
module.exports = { build };
