// Anonymous deterministic public-site acceptance; NOT native Browser or Render admin.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
if(!process.env.WM_PUBLIC_RELEASE_QA){console.log('Public release QA skipped: set WM_PUBLIC_RELEASE_QA explicitly.');process.exit(0);}
const {chromium}=require('playwright');
const out=path.resolve(__dirname,'../output/public-release'),root=path.resolve(__dirname,'../wandermind-studio/frontend');
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const comparable=(bytes,asset)=>/\.(js|json)$/.test(asset)?bytes.toString('utf8').replace(/\r\n/g,'\n'):bytes;
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true});const report={capturedAt:new Date().toISOString(),surface:'Anonymous deterministic Playwright; NOT native Browser/Render admin',matrix:[],assets:[],writes:0};
try{const context=await browser.newContext();report.blockedNonGet=[];await context.route('**/*',route=>{const req=route.request();if(req.method()!=='GET'){const url=new URL(req.url());report.blockedNonGet.push({method:req.method(),origin:url.origin,path:url.pathname});return route.abort();}if(new URL(req.url()).pathname.startsWith('/api/'))return route.abort();return route.continue();});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
for(const asset of ['assets/data/bali-extensions.json','assets/data/bali-food.json','assets/js/bali-food-taxonomy.js','assets/images/web/penida-snorkeling-coast.webp','assets/images/web/bali-nasi-campur.webp']){const res=await page.goto('https://wandermind.cc/'+asset,{timeout:20000});assert.equal(res.status(),200,asset);const received=await res.body();assert.equal(hash(comparable(received,asset)),hash(comparable(fs.readFileSync(path.join(root,asset)),asset)),asset+' served content differs after LF normalization');report.assets.push({path:asset,status:200,sha256:hash(received),match:/\.(js|json)$/.test(asset)?'LF-normalized source parity':'exact binary parity'});}
for(const width of (process.env.WM_PUBLIC_GALLERY_ONLY?[]:[320,390,768,1440])){await page.setViewportSize({width,height:900});for(const lang of ['zh','en','ja','ko','id']){await page.goto('https://wandermind.cc/dining.html?lang='+lang+'&route=R1&day=0',{waitUntil:'domcontentloaded',timeout:20000});await page.locator('.food-card').first().waitFor({timeout:15000});assert.ok(await page.locator('#food-cuisine option').count()>1);assert.ok(await page.locator('#food-scene option').count()>1);assert.ok(!/undefined/.test(await page.locator('main').innerText()));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth),0);report.matrix.push({page:'dining',width,lang,overflow:0,cuisineOptions:await page.locator('#food-cuisine option').count(),sceneOptions:await page.locator('#food-scene option').count()});if(lang==='zh')await page.screenshot({path:path.join(out,'food-'+width+'.png')});}}
await page.setViewportSize({width:390,height:844});await page.goto('https://wandermind.cc/bali.html?lang=zh&route=R1',{waitUntil:'domcontentloaded',timeout:20000});
for(const id of ['penida-west','penida-east','penida-snorkeling'])await page.locator('[data-extension-add="'+id+'"]').waitFor({state:'attached',timeout:15000});
const photo=page.locator('.bali-shot[data-place-name="Balinese nasi campur"]');await photo.waitFor({state:'attached',timeout:15000});
const toggle=page.locator('#gallery [data-mobile-section-toggle]');if(await toggle.getAttribute('aria-expanded')==='false')await toggle.click();
await page.locator('#bali-filter-sheet-open').click();await page.locator('[data-filter="food-dining"]').click();await page.locator('.is-primary[data-gallery-filter-close]').click();await photo.scrollIntoViewIfNeeded();await photo.locator('img').evaluate(image=>image.decode());await photo.click();await page.locator('#bali-place-modal').waitFor({state:'visible'});assert.ok((await page.locator('#bali-place-modal').innerText()).includes('CC BY-SA 3.0'));await page.locator('#bali-place-image').evaluate(image=>image.decode());await page.screenshot({path:path.join(out,'food-album-live.png')});await page.locator('.bali-place-close').click();
await page.locator('#bali-filter-sheet-open').click();await page.locator('[data-gallery-filter-reset]').click();await page.locator('.is-primary[data-gallery-filter-close]').click();
const marine=page.locator('.bali-shot[data-full-image*="penida-snorkeling-coast"]');await marine.scrollIntoViewIfNeeded();await marine.locator('img').evaluate(image=>image.decode());await marine.click();await page.locator('#bali-place-modal').waitFor({state:'visible'});assert.ok((await page.locator('#bali-place-modal').innerText()).includes('CC BY 2.0'));await page.locator('#bali-place-image').evaluate(image=>image.decode());await page.screenshot({path:path.join(out,'marine-album-live.png')});report.gallery={publishedPhotos:2,foodCredit:'CC BY-SA 3.0',marineCredit:'CC BY 2.0',decode:true,routeExtensions:3};
assert.deepEqual(errors,[]);assert.equal(report.writes,0);report.pageErrors=0;report.result='passed public parity,'+report.matrix.length+'Foodcases and two credited Portfolio photos';
}catch(e){report.failure=e.message;process.exitCode=1;}finally{fs.writeFileSync(path.join(out,'result.json'),JSON.stringify(report,null,2));await browser.close();}console.log(JSON.stringify(report));})();
