module.exports = {
  "zh": {
    "historyTitle": "继续上次的旅行讨论",
    "historySub": "对话保存在同一 WanderMind 账号中。",
    "loading": "正在读取…",
    "retry": "重试",
    "emptyHistory": "还没有保存的对话",
    "emptyHint": "发送第一条旅行问题后，会自动保存在这里。",
    "delete": "删除",
    "deleteTitle": "删除对话",
    "deleteAsk": "删除后无法恢复，确定继续吗？",
    "deleteFailed": "删除失败",
    "historyFailed": "历史加载失败",
    "ok": "确定",
    "cancel": "取消",
    "galleryTitle": "岛屿上的真实瞬间",
    "gallerySub": "先看看巴厘岛原本的样子，再决定你想抵达哪里。照片来自已授权项目图库与已发布作品。",
    "all": "全部",
    "landscapes": "自然风景",
    "culture": "文化与寺庙",
    "experiences": "在地体验",
    "galleryLoading": "正在整理岛屿照片…",
    "galleryFailed": "作品集暂时无法加载",
    "reload": "重新加载",
    "emptyGallery": "这个分类暂时还没有已发布照片。",
    "imageFailed": "图片暂时无法加载",
    "viewPlace": "查看地点与更多景色",
    "viewPhoto": "查看照片说明",
    "count": "张照片",
    "saveHint": "长按图片可保存",
    "tapHint": "点开查看地点",
    "placeLoading": "正在读取地点与照片…",
    "photoEmpty": "这个地点暂时没有照片",
    "liveNote": "照片用于了解环境；出发前请确认天气、开放时间、门票与预约。",
    "currentPhoto": "当前照片",
    "exact": "真实地点照片",
    "reference": "区域或体验参考图",
    "source": "复制图片来源链接",
    "official": "复制官方地点链接",
    "booking": "复制预约链接",
    "back": "返回路线",
    "route": "路线",
    "notFound": "没有找到这个地点或照片",
    "placeDefault": "这里是路线中的一个真实地点，出发前请再次确认开放时间与现场条件。",
    "placeFailed": "地点详情暂时无法加载",
    "copied": "链接已复制",
    "copyFailed": "复制失败，请重试"
  },
  "en": {
    "historyTitle": "Continue your travel conversation",
    "historySub": "Your conversations stay with your WanderMind account.",
    "loading": "Loading…",
    "retry": "Retry",
    "emptyHistory": "No conversations yet",
    "emptyHint": "Your first travel question will start a saved conversation.",
    "delete": "Delete",
    "deleteTitle": "Delete conversation",
    "deleteAsk": "This cannot be undone. Delete?",
    "deleteFailed": "Could not delete",
    "historyFailed": "Could not load history",
    "ok": "OK",
    "cancel": "Cancel",
    "galleryTitle": "Moments from the island",
    "gallerySub": "Explore Bali in photos and find places for your trip.",
    "all": "All",
    "landscapes": "Landscapes",
    "culture": "Culture & temples",
    "experiences": "Experiences",
    "galleryLoading": "Loading island photos…",
    "galleryFailed": "Could not load photos",
    "reload": "Reload",
    "emptyGallery": "No photos in this category yet.",
    "imageFailed": "Image unavailable",
    "viewPlace": "See the place and more photos",
    "viewPhoto": "Read about this photo",
    "count": "photos",
    "saveHint": "Hold a photo to save",
    "tapHint": "Tap to explore",
    "placeLoading": "Loading place and photos…",
    "photoEmpty": "No photos for this place yet",
    "liveNote": "Photos help you explore. Check weather, hours, tickets and bookings before visiting.",
    "currentPhoto": "Current photo",
    "exact": "Photo of this place",
    "reference": "Area or experience reference",
    "source": "Copy photo source link",
    "official": "Copy official place link",
    "booking": "Copy booking link",
    "back": "Back to routes",
    "route": "Route",
    "notFound": "Place or photo not found",
    "placeDefault": "Check opening hours and local conditions before visiting.",
    "placeFailed": "Could not load place details",
    "copied": "Link copied",
    "copyFailed": "Could not copy. Retry."
  },
  "ja": {
    "historyTitle": "前回の旅の相談を続ける",
    "historySub": "会話はWanderMindアカウントに保存されます。",
    "loading": "読み込み中…",
    "retry": "再試行",
    "emptyHistory": "会話はまだありません",
    "emptyHint": "旅の質問を送ると、ここに会話が保存されます。",
    "delete": "削除",
    "deleteTitle": "会話を削除",
    "deleteAsk": "元に戻せません。削除しますか？",
    "deleteFailed": "削除できませんでした",
    "historyFailed": "履歴を読み込めませんでした",
    "ok": "OK",
    "cancel": "キャンセル",
    "galleryTitle": "島のひととき",
    "gallerySub": "バリの写真から、訪れたい場所を探しましょう。",
    "all": "すべて",
    "landscapes": "自然風景",
    "culture": "文化と寺院",
    "experiences": "現地体験",
    "galleryLoading": "島の写真を読み込み中…",
    "galleryFailed": "写真を読み込めませんでした",
    "reload": "再読み込み",
    "emptyGallery": "このカテゴリにはまだ写真がありません。",
    "imageFailed": "画像を読み込めません",
    "viewPlace": "場所とほかの写真を見る",
    "viewPhoto": "写真の説明を見る",
    "count": "枚",
    "saveHint": "写真を長押しして保存",
    "tapHint": "タップして詳細へ",
    "placeLoading": "場所と写真を読み込み中…",
    "photoEmpty": "この場所にはまだ写真がありません",
    "liveNote": "写真で雰囲気を確認できます。天候・営業時間・入場券・予約は訪問前にご確認ください。",
    "currentPhoto": "表示中の写真",
    "exact": "この場所の写真",
    "reference": "地域・体験の参考写真",
    "source": "写真の出典リンクをコピー",
    "official": "公式サイトのリンクをコピー",
    "booking": "予約リンクをコピー",
    "back": "ルートに戻る",
    "route": "ルート",
    "notFound": "場所または写真が見つかりません",
    "placeDefault": "訪問前に営業時間と現地の状況をご確認ください。",
    "placeFailed": "場所の詳細を読み込めませんでした",
    "copied": "リンクをコピーしました",
    "copyFailed": "コピーできませんでした。再試行してください。"
  },
  "ko": {
    "historyTitle": "지난 여행 대화 이어가기",
    "historySub": "대화는 WanderMind 계정에 저장됩니다.",
    "loading": "불러오는 중…",
    "retry": "다시 시도",
    "emptyHistory": "아직 대화가 없습니다",
    "emptyHint": "첫 여행 질문을 보내면 여기에 대화가 저장됩니다.",
    "delete": "삭제",
    "deleteTitle": "대화 삭제",
    "deleteAsk": "되돌릴 수 없습니다. 삭제할까요?",
    "deleteFailed": "삭제하지 못했습니다",
    "historyFailed": "기록을 불러오지 못했습니다",
    "ok": "확인",
    "cancel": "취소",
    "galleryTitle": "섬에서 만난 순간",
    "gallerySub": "발리 사진을 보며 가고 싶은 곳을 찾아보세요.",
    "all": "전체",
    "landscapes": "자연 풍경",
    "culture": "문화와 사원",
    "experiences": "현지 체험",
    "galleryLoading": "섬 사진 불러오는 중…",
    "galleryFailed": "사진을 불러오지 못했습니다",
    "reload": "다시 불러오기",
    "emptyGallery": "이 분류에는 아직 사진이 없습니다.",
    "imageFailed": "이미지를 불러올 수 없습니다",
    "viewPlace": "장소와 더 많은 사진 보기",
    "viewPhoto": "사진 설명 보기",
    "count": "장",
    "saveHint": "사진을 길게 눌러 저장",
    "tapHint": "눌러서 장소 보기",
    "placeLoading": "장소와 사진 불러오는 중…",
    "photoEmpty": "이 장소의 사진은 아직 없습니다",
    "liveNote": "사진으로 분위기를 살펴보세요. 방문 전 날씨·운영 시간·입장권·예약을 확인하세요.",
    "currentPhoto": "현재 사진",
    "exact": "실제 장소 사진",
    "reference": "지역·체험 참고 사진",
    "source": "사진 출처 링크 복사",
    "official": "공식 장소 링크 복사",
    "booking": "예약 링크 복사",
    "back": "경로로 돌아가기",
    "route": "경로",
    "notFound": "장소 또는 사진을 찾을 수 없습니다",
    "placeDefault": "방문 전 운영 시간과 현장 상황을 확인하세요.",
    "placeFailed": "장소 정보를 불러오지 못했습니다",
    "copied": "링크 복사됨",
    "copyFailed": "복사하지 못했습니다. 다시 시도하세요."
  },
  "id": {
    "historyTitle": "Lanjutkan percakapan perjalanan",
    "historySub": "Percakapan tersimpan di akun WanderMind Anda.",
    "loading": "Memuat…",
    "retry": "Coba lagi",
    "emptyHistory": "Belum ada percakapan",
    "emptyHint": "Kirim pertanyaan perjalanan pertama untuk mulai menyimpan percakapan.",
    "delete": "Hapus",
    "deleteTitle": "Hapus percakapan",
    "deleteAsk": "Tidak dapat dibatalkan. Hapus?",
    "deleteFailed": "Gagal menghapus",
    "historyFailed": "Riwayat gagal dimuat",
    "ok": "OK",
    "cancel": "Batal",
    "galleryTitle": "Momen dari pulau",
    "gallerySub": "Lihat foto Bali dan temukan tempat untuk perjalanan Anda.",
    "all": "Semua",
    "landscapes": "Pemandangan",
    "culture": "Budaya & pura",
    "experiences": "Pengalaman",
    "galleryLoading": "Memuat foto pulau…",
    "galleryFailed": "Foto gagal dimuat",
    "reload": "Muat ulang",
    "emptyGallery": "Belum ada foto di kategori ini.",
    "imageFailed": "Gambar belum tersedia",
    "viewPlace": "Lihat tempat dan foto lainnya",
    "viewPhoto": "Lihat keterangan foto",
    "count": "foto",
    "saveHint": "Tekan lama foto untuk menyimpan",
    "tapHint": "Ketuk untuk melihat tempat",
    "placeLoading": "Memuat tempat dan foto…",
    "photoEmpty": "Belum ada foto tempat ini",
    "liveNote": "Foto membantu mengenal tempat. Periksa cuaca, jam buka, tiket, dan reservasi sebelum berkunjung.",
    "currentPhoto": "Foto saat ini",
    "exact": "Foto tempat ini",
    "reference": "Referensi area atau pengalaman",
    "source": "Salin tautan sumber foto",
    "official": "Salin tautan resmi tempat",
    "booking": "Salin tautan reservasi",
    "back": "Kembali ke rute",
    "route": "Rute",
    "notFound": "Tempat atau foto tidak ditemukan",
    "placeDefault": "Periksa jam buka dan kondisi setempat sebelum berkunjung.",
    "placeFailed": "Detail tempat gagal dimuat",
    "copied": "Tautan disalin",
    "copyFailed": "Gagal menyalin. Coba lagi."
  }
};
